spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/electric
      username: root
      password: 674355501love

mybatis-plus:
  typeAliasesPackage: com.fast.dao.entity
  global-config:
    db-config:
      field-strategy: NOT_NULL
      column-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true